# Generated by Django 4.2.6 on 2023-10-20 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AD', '0002_commetn_delete_responce'),
    ]

    operations = [
        migrations.AddField(
            model_name='commetn',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Видимость статьи'),
        ),
        migrations.AlterField(
            model_name='commetn',
            name='commentAD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_AD', to='AD.ad', verbose_name='статья'),
        ),
        migrations.AlterField(
            model_name='commetn',
            name='text',
            field=models.TextField(verbose_name='текст комментария'),
        ),
    ]
