# Generated by Django 4.2.6 on 2023-10-20 12:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AD', '0003_commetn_status_alter_commetn_commentad_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commetn',
            new_name='Comment',
        ),
    ]
