# Generated by Django 4.2.6 on 2023-10-21 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AD', '0005_alter_comment_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='status',
        ),
    ]
